language: ruby

rvm:
  - 2.0.0

script:
  - RAILS_ENV=test COVERAGE=true bundle exec rake --trace db:migrate spec
  - RAILS_ENV=test COVERAGE=true bundle exec cucumber
  - RAILS_ENV=test COVERAGE=true bundle exec cucumber touch

branches:
  only:
    - master
    - production

notifications:
  email:
    recipients:
      - gmacie@hotmail.com
      - jasnow@hotmail.com
      - jamesdabbs@gmail.com
    on_success: change
    on_failure: always
