language: ruby
rvm:
- 2.1.0
script:
- RAILS_ENV=test COVERAGE=true bundle exec rake --trace db:migrate spec cucumber
- RAILS_ENV=test COVERAGE=true bundle exec cucumber -p javascript
branches:
  only:
  - master
  - production
notifications:
  email:
    recipients:
    - jamesdabbs@gmail.com
    on_success: change
    on_failure: always
